# Generated by Django 5.2.5 on 2025-09-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("recipes", "0004_recipe_created_by_recipe_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="recipes.recipe"
            ),
        ),
    ]
