# Generated by Django 5.2.5 on 2025-08-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="complementary",
            field=models.ManyToManyField(blank=True, to="recipes.recipe"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, to="recipes.tag"),
        ),
    ]
