# Generated by Django 5.2.5 on 2025-09-05 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipe_complementary_alter_recipe_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepingredient",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stepingredient",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipes.unit",
            ),
        ),
    ]
